version: "3.9"

x-common-variables: &common-variables
  POSTGRES_DB: $POSTGRES_DB
  POSTGRES_USER: $POSTGRES_USER
  POSTGRES_PASSWORD: $POSTGRES_PASSWORD
  POSTGRES_SERVER: $POSTGRES_SERVER
  DB_PORT: $DB_PORT
  SECRET_KEY: $SECRET_KEY
  REDIS_HOST: $REDIS_HOST
  DEBUG: true
  ALLOWED_HOSTS: $ALLOWED_HOSTS


services:
  web:
    image: gmoroz/tournament_web:$GITHUB_REF_NAME-$GITHUB_RUN_ID
    environment:
      *common-variables
    ports:
      - 80:80
    volumes:
      - logs:/code/logs
      - staticdata:/usr/src/app/static_files
    depends_on:
      db:
        condition: service_healthy
      redis_db:
        condition: service_started


  db:
    image: postgres:latest
    environment:
      *common-variables
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB'"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis_db:
    image: redis:latest
    restart: always
    volumes:
      - redis_data:/data

  nginx:
    image: nginx:latest
    ports:
      - "3000:3000"
    depends_on:
      - web

volumes:
  postgres_data:
  redis_data:
  staticdata:
  logs:
