version: "3.9"

services:
  web:
    build: .
    env_file:
      .env.docker
    ports:
      - 80:80
    volumes:
      - logs:/code/logs
      - staticdata:/usr/src/app/static_files
    depends_on:
      db:
        condition: service_healthy
      redis_db:
        condition: service_started

  db:
    image: postgres:latest
    env_file:
      .env.docker
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB'"]
      interval: 5s
      timeout: 5s
      retries: 5


  redis_db:
    image: redis:latest
    restart: always
    volumes:
      - redis_data:/data

  nginx:
    image: nginx:latest
    ports:
      - "3000:3000"
    depends_on:
      - web

volumes:
  postgres_data:
  redis_data:
  staticdata:
  logs:
