# Generated by Django 4.1.7 on 2023-02-15 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Titul',
            fields=[
                (
                    'id', models.BigAutoField(
                        auto_created=True,
                        primary_key=True, serialize=False, verbose_name='ID',
                    ),
                ),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                (
                    'id', models.BigAutoField(
                        auto_created=True,
                        primary_key=True, serialize=False, verbose_name='ID',
                    ),
                ),
                ('name', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('coach', models.CharField(max_length=255)),
                ('points', models.PositiveIntegerField()),
                ('tituls', models.ManyToManyField(to='main.titul')),
            ],
        ),
        migrations.CreateModel(
            name='Calendar',
            fields=[
                (
                    'id', models.BigAutoField(
                        auto_created=True,
                        primary_key=True, serialize=False, verbose_name='ID',
                    ),
                ),
                ('date_of_the_match', models.DateField()),
                ('main_judge', models.CharField(max_length=100)),
                ('result', models.CharField(default=None, max_length=5, null=True)),
                ('teams', models.ManyToManyField(to='main.team')),
            ],
        ),
    ]
