# Generated by Django 4.1.7 on 2023-02-15 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calendar',
            name='teams',
        ),
        migrations.RemoveField(
            model_name='team',
            name='tituls',
        ),
        migrations.AddField(
            model_name='calendar',
            name='teams',
            field=models.ManyToManyField(to='main.team'),
        ),
        migrations.AddField(
            model_name='team',
            name='tituls',
            field=models.ManyToManyField(to='main.titul'),
        ),
    ]
